### ISSUE TITLE
Tab completion overwrites '->' in C++ file

### ISSUE THREAD

**Issue by jbarik** [hrsh7th/nvim-compe#193] opened 2021-02-19 12:25 UTC
Thank you for the beautiful plugin. Thanks to this, now I'm moving to neovim's in-built lsp

![completion_issue](https://user-images.githubusercontent.com/22386546/108504071-58e8fb00-72db-11eb-9aab-f0547f36e8c2.gif)

As shown above, you can see while completing the first item(followed by '.') it works beautifully. However, for the second completion(followed by '->'), on selecting an item it overwrites '->'.

Please let me know if I need to provide any other information.

**Comment by hrsh7th** [comment] 2021-02-19 12:27
Thank you.
Yes. It should be fixed by #186

**Comment by hrsh7th** [comment] 2021-02-22 08:29
Could you test with the latest master?

I don't know it was fixed but I hope to know the result.

**Comment by jbarik** [comment] 2021-02-22 11:14
The issue of overwriting '->' is gone. But  I see a new issue. As, I continue typing, the popup is not updated and I am not getting the best match.
![lsp_issue2](https://user-images.githubusercontent.com/22386546/108700792-246c7d80-752d-11eb-9067-ed7793a85f4c.gif)

**Comment by hrsh7th** [comment] 2021-02-22 11:21
Thank you for your confirmation.
It's weird.
Could you provide simple reproducible cpp file?

**Comment by jbarik** [comment] 2021-02-22 16:46
I am seeing this issue in a regular file(without lsp)

![completion_issue](https://user-images.githubusercontent.com/22386546/108740355-965bbb80-755b-11eb-8232-a6350730976c.gif)

**Comment by hrsh7th** [comment] 2021-02-22 16:49
It's really weird... I can't reproduce it.


https://user-images.githubusercontent.com/629908/108740722-51df1880-7579-11eb-811a-2b525280d14c.mp4

**Comment by jbarik** [comment] 2021-02-23 04:18
May be there is something wrong with my settings or some other plugin. Any idea how to debug, where to start?

**Comment by hrsh7th** [comment] 2021-02-23 04:22
If you can, I want to get the minimal config based on https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim .

**Comment by jbarik** [comment] 2021-02-23 08:28
With a minimalist config, I could not reproduce the issue.

However, with latest update, the issue is gone.

**Comment by hrsh7th** [comment] 2021-02-23 08:39
Good to hear. Thank you for your confirmation.

**Closed by hrsh7th** 2021-02-23 08:39 UTC
Labels: bug

**Comment by jbarik** [comment] 2021-02-23 09:32
The issue is gone for non-lsp completion(e.g. path completion). 

Unfortunately the issue is still there in cpp file. I'll find out more and probably create a new issue.
