### ISSUE TITLE
when completion confirm the signature will auto insert to buffer

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/nvim-compe#163] opened 2021-02-10 13:15 UTC
https://user-images.githubusercontent.com/41671631/107514808-1e010c00-6be5-11eb-900a-37eeecbcb2e5.mov

**Comment by hrsh7th** [comment] 2021-02-10 14:07
lol.

I can't understand this behavior.
Could you create minimal config?

**Comment by oberblastmeister** [comment] 2021-02-10 22:16
This happens to me too

**Comment by oberblastmeister** [comment] 2021-02-10 22:20
For me the latest two commits made this happen, resetting to a85c6461ddf73fbe307a73b06855e336e298b152 fixes it.

**Comment by hrsh7th** [comment] 2021-02-11 03:29
@oberblastmeister Thank you for information.
Could you check this problem still happen on latest master?

**Comment by oberblastmeister** [comment] 2021-02-11 15:05
@hrsh7th the problem is fixed on the latest master

**Comment by hrsh7th** [comment] 2021-02-11 15:11
Thank you for your confirmation.

**Closed by hrsh7th** 2021-02-11 15:11 UTC
Labels: bug, high-priority, needs-more-info
