### ISSUE TITLE
Error when calling the compe#complete function - "Vim:E523: Not allowed here"

### ISSUE THREAD

**Issue by DilanGMB** [hrsh7th/nvim-compe#216] opened 2021-02-24 17:58 UTC
Today morning I updated my plugins (including compe), and I noticed an error in the execution of the compe#complete function when I started writing code.
The function doesn't do its job correctly, returning only "-1" when I try to execute it.
It's quite strange because it was working fine yesterday.

Note that when I set myself to dc6ba80, the error disappears, working correctly.

![Screenshot from 2021-02-24 12-46-13](https://user-images.githubusercontent.com/65829671/109044053-f2c7f380-769f-11eb-8bb3-0b51acc7737b.png)

**Comment by YaBoiBurner** [comment] 2021-02-24 23:09
Could you possibly provide your compe config?

I've been trying to diagnose this and haven't had much success (partially because I might be running into another interrelated issue) so something else to go off of would be much appreciated.

**Comment by DilanGMB** [comment] 2021-02-24 23:24
of course, my configuration is not out of the configuration stipulated in the guide, but this is a screenshot.
I clarify that it is the only thing I have configured with the plugin, in addition to its noremaps, which, by the way, are the same as in the guide.

![Screenshot from 2021-02-24 18-19-59](https://user-images.githubusercontent.com/65829671/109079607-2ec57d80-76cd-11eb-9dc4-06d709d0afa7.png)

**Comment by hrsh7th** [comment] 2021-02-25 02:14
@DilanGMB Could you provide your full config?
I can't reproduce it. (But I've updated it recently so this problem has a possibility to occur.

**Comment by DilanGMB** [comment] 2021-02-25 03:42
Of course, look at this is my repository with all the configurations I have, it's simple
https://github.com/DilanGMB/nvim

**Comment by hrsh7th** [comment] 2021-02-25 04:00
Ah. Current implementation is like as throwing exception. So it's nvim-compe's bug.

But in my environment, it seems to work correctly. Probably, it due to the latest nvim.
I will update it.

**Comment by hrsh7th** [comment] 2021-02-25 04:01
This issue should be fixed.
https://github.com/hrsh7th/nvim-compe/commit/b845407c5b407041a12d4d83251f38f44b1792d4

**Closed by hrsh7th** 2021-02-25 04:01 UTC
Labels: bug, high-priority

**Comment by DilanGMB** [comment] 2021-02-25 04:11
it's great, now it works properly!
