### ISSUE TITLE
Feature request: configurable debounce on LSP (or all) source requests (for perf)

### ISSUE THREAD

**Issue by marcelbeumer** [hrsh7th/nvim-compe#388] opened 2021-05-25 14:27 UTC
#### Is your feature request related to a problem? Please describe.

Because there is no delay/debounce on source calls (there is on source results), compe (with autocomplete set to true) will do a lot of unnecessary LSP calls while typing, one for every keystroke. I noticed on my machine using neovim builtin LSP on my TypeScript codebase: my macbook was making noise even faster than normally :-)

Neovim's builtin LSP does it's own internal debouncing for LSP requests, but any incoming `textDocument/completion` requests like the ones from compe will force to flush all the pending requests because LSP can not operate on stale documents. 

#### Describe the solution you'd like

I would like a configurable and optional debounce for source calls, at least for LSP but probably makes sense for every input type (?). With this configurable debounce value I could set in such a way that unnecessary `textDocument/completion` requests are (a bit more) limited.

#### Describe alternatives you've considered

Not using `autocomplete: true` and go trigger based, which I'm doing now and might also end up as my preference. But probably many other people use `autocomplete: true` and also have the same issue with their LSP server instances getting too many requests.

**Comment by chmln** [comment] 2021-05-29 16:17
This is also one of the last things preventing me from using nvim-compe, as both completion-nvim and coc.nvim implement debounced LSP requests. Would love to see this land as it will improve both performance and efficiency.

**Comment by hrsh7th** [comment] 2021-05-30 15:41
I've already provided "throttle_time" to throttling completion requests.
Is this not enough?

**Comment by AndreaHasani** [comment] 2021-05-31 20:00
@hrsh7th Hello,
First thanks for this amazing plugin and the work you have done on it.

From my testing (changing the throttle_time from 80 to 1000 just for testing), the lsp server is hit just as hard.

The way I tested this is by just navigating through the autocomplete with c-n and c-p, this causes the plugin to hit the server for every scroll

**Comment by hrsh7th** [comment] 2021-06-01 03:54
Yes. The LSP spec has `completionItem/resolve` request that resolve completionItem's documentation, additionalTextEdits etc.

I can implement debounce to `completionItem/resolve` but it will introduce flicker maybe.

**Comment by hrsh7th** [comment] 2021-06-01 03:56
I think this is not a problem if `textDocument/completion` request is not sent frequently.

**Comment by marcelbeumer** [comment] 2021-06-01 07:48
hi @hrsh7th, I don't oversee the other use cases, but the reason I created this feature request is that I noticed that for every keystroke in normal mode (always; also without the compe popup showing) compe will send a `textDocument/completion` request (nothing else). These requests are not debounced in any way and more or less "flood" the LSP server in that way.

A short look at the source gave the impression that compe debounces the *results* of LSP requests, but the not LSP requests themselves.

**Comment by hrsh7th** [comment] 2021-06-01 07:55
@marcelbeumer What did you use langserver for testing?

If the langserver is `typescript-language-server`, it seems a bug of compe.

**Comment by marcelbeumer** [comment] 2021-06-01 07:57
@hrsh7th yes on a TS codebase using `theia-ide/typescript-language-server`

**Comment by marcelbeumer** [comment] 2021-06-02 21:15
> hi @hrsh7th, I don't oversee the other use cases, but the reason I created this feature request is that I noticed that for every keystroke in normal mode

sorry meant insert mode of course

**Comment by hrsh7th** [comment] 2021-06-10 14:30
I can't reproduce on typescript-language-server.
Please reprodusible step.
@marcelbeumer

**Comment by marcelbeumer** [comment] 2021-06-25 17:35
Hi @hrsh7th, thanks for looking into it! This should be with any language server, not TypeScript specific.

When you add some logging just before the `client.request('textDocument/completion'` call is done in `lua/compe_nvim_lsp/source.lua` you will see that requests are send immediately without debounce, regardless of your settings. For example:

https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe_nvim_lsp/source.lua#L42
```
  local fd = io.open("lsplog.txt", "a")
  fd:write("LSP textDocument/completion\n")
  fd:close()

  self.client.request('textDocument/completion', request, function(err, _, response)
```

And then `tail -f lsplog.txt` while you are typing (with compe setting `autocomplete = true` of course). You should see logging happening for each keystroke, even with a  `throttle_time = 1000` for example.

**Comment by timsofteng** [comment] 2021-07-06 22:40
Any news about it?

**Comment by hrsh7th** [comment] 2021-07-07 03:23
No. nvim-compe does not send request on each keypress.

Please look into `tail -f ~/.cache/nvim/lsp.log | grep textDocument/completion`.

**Comment by marcelbeumer** [comment] 2021-07-07 08:20
@hrsh7th how do you get any `textDocument/completion` to show up in `~/.cache/nvim/lsp.log`? I did `lua vim.lsp.set_log_level("debug")` but I see almost only `textDocument/publishDiagnostics`. Even grep on `complete` gives me nothing.

Did you try the logging on compe source level that I suggested?

**Comment by mjlbach** [comment] 2021-07-07 08:21
Try "trace"

**Comment by hrsh7th** [comment] 2021-07-07 08:33
@mjlbach Thank you.

Yes. you should use `vim.lsp.set_log_level("trace")`

**Comment by marcelbeumer** [comment] 2021-07-07 08:46
Thanks, trace works. I'm getting a `textDocument/completion` for each keypress in insert mode. See screenshots below. Links to code repo and vim config too. I understand it's not a minimal test case, let me know if I can provide something and how that should look like from the vim (config) side of things.

my compe setup
```lua
  require'compe'.setup {
    enabled = true;
    autocomplete = false;
    debug = false;
    min_length = 1;
    preselect = 'enable';
    throttle_time = 80;
    source_timeout = 2000;
    resolve_timeout = 2000;
    incomplete_delay = 400;
    max_abbr_width = 100;
    max_kind_width = 100;
    max_menu_width = 100;
    documentation = true;

    source = {
      -- path = true;
      -- buffer = true;
      -- calc = true;
      nvim_lsp = true;
      -- nvim_lua = true;
      -- vsnip = true;
      -- ultisnips = true;
    };
  }
  vim.lsp.set_log_level("trace")
```

With `autocomplete=true` like above, I go into insert mode and just type 4 times `j`:
![autocomplete_on](https://user-images.githubusercontent.com/111366/124728793-28af9b00-df10-11eb-9359-1b238a76c3b2.jpg)

Same but with `autocomplete=false`:
![autocomplete_off](https://user-images.githubusercontent.com/111366/124728924-4b41b400-df10-11eb-83e2-17105d4b1d13.jpg)



my complete nvim config: https://github.com/marcelbeumer/dotfiles/tree/master/nvim
the TypeScript code: https://github.com/marcelbeumer/jtd-codegen-setup

**Comment by hrsh7th** [comment] 2021-07-07 08:54
Awesome. I will investigate it.

**Comment by marcelbeumer** [comment] 2021-07-07 08:58
I now see that `tsserver` is only getting a single completion (good) and the EFM multiple (weird). When I disable all language server except `tsserver` I only get the completion calls when I would expect it.

**Comment by marcelbeumer** [comment] 2021-07-07 09:07
And also when I again do the logging on compe source level I see that without efm it is *not* doing requests for every keypress, and with efm enabled it *does* do requests for every keypress.

**Comment by marcelbeumer** [comment] 2021-07-07 09:53
Sorry in advance @hrsh7th if this turns out to be not compe but nvim (lsp) or efm. Tried to dig a bit deeper and it seems that efm (on my TS code buffer) correctly resolves to *not* having completion support. 

Log:
```
[ INFO ] 2021-07-07T11:31:53+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:855 ]	"LSP[efm]"	"initialized"	{  
resolved_capabilities = {    call_hierarchy = false,    code_action = false,    code_lens = false,    code_lens_resolve = false,    
completion = false,    declaration = false,    document_formatting = true,    document_highlight = false,    
document_range_formatting = false,    document_symbol = false,    execute_command = false,    find_references = false,    
goto_definition = true,    hover = false,    implementation = false,    rename = false,    signature_help = false,    
signature_help_trigger_characters = {},    text_document_did_change = 1,    text_document_open_close = true,    
text_document_save = true,    text_document_save_include_text = false,    text_document_will_save = false,    
text_document_will_save_wait_until = false,    type_definition = false,    workspace_folder_properties = {      
changeNotifications = true,      supported = true    },    workspace_symbol = false  }}
```

Could it be that compe is not (and should?) check if the lsp client has completion capabilities? I only see checking server capabilities for determining trigger chars (https://github.com/hrsh7th/nvim-compe/blob/964ba4adcb23c5d48312b5002818d1c22e914dc2/lua/compe_nvim_lsp/source.lua#L25), and creating sources for every client (https://github.com/hrsh7th/nvim-compe/blob/964ba4adcb23c5d48312b5002818d1c22e914dc2/lua/compe_nvim_lsp/init.lua#L23). 

But maybe it's zero overhead to ask for completion to clients that don't have support (nvim would notice?) and therefore would be just polish? Just thinking out loud.

Tried to tinker with the on_attach of lspconfig but did not do anything either 
```
    on_attach = function(lsp_client, bufnr)
      lsp_client.resolved_capabilities.completionProvider = nil
      lsp_client.resolved_capabilities.completion = nil
      ...
    end,
```

**Comment by hrsh7th** [comment] 2021-07-07 10:06
Thank you very much!

I found the cause and fixed it.

**Comment by hrsh7th** [comment] 2021-07-07 10:07
It was a critical bug. Again, Thank you very much.

**Comment by marcelbeumer** [comment] 2021-07-07 10:24
🎉 Welcome, and thank you too! :)

**Comment by hrsh7th** [comment] 2021-07-07 10:58
If this issue is solved, feel free to close it.

**Closed** 2021-07-07 19:16 UTC
