### ISSUE TITLE
Documents are not displayed correctly

### ISSUE THREAD

**Issue by tamago324** [hrsh7th/nvim-compe#53] opened 2020-12-15 14:00 UTC
The first time it works fine, but after the second time it does not seem to display correctly.

![compe_issue](https://user-images.githubusercontent.com/16581287/102224061-d59cd900-3f28-11eb-9c3b-17e51b8101f0.gif)

- `nvim --version`: `NVIM v0.5.0-dev+941-g9c56d8e5f`
- Operating system/version: `Ubuntu 18.04` (WSL2)

vimrc

```vim
set encoding=utf-8
scriptencoding utf-8

filetype plugin indent on
if has('vim_starting')
  let s:pluin_manager_dir='~/.config/nvim/.plugged/vim-plug'
  execute 'set runtimepath+=' . s:pluin_manager_dir
endif

call plug#begin('~/.config/nvim/.plugged')
Plug 'hrsh7th/nvim-compe'
Plug 'neovim/nvim-lspconfig'
Plug 'sainnhe/gruvbox-material'
call plug#end()

set nobackup
set nowritebackup
set noswapfile
set updatecount=0
set backspace=indent,eol,start
language messages en_US.utf8

set termguicolors

set bg=dark
colorscheme gruvbox-material

lua << EOF
require'compe'.setup {
  enabled = true,

  source = {
    nvim_lsp = true,
  }
}

require'lspconfig'.vimls.setup{}
EOF
```

Is there something I'm missing in the settings?

Please take a look when you have time.

**Comment by hrsh7th** [comment] 2020-12-15 14:49
Reproduced.

Hm... I don't know the reason. I will investigate it.

**Comment by hrsh7th** [comment] 2020-12-15 15:56
I found the reason.

`set autoread` will solve this problem.

え〜

**Comment by hrsh7th** [comment] 2020-12-15 18:20
Fixed in https://github.com/hrsh7th/nvim-compe/commit/d1abc8e6638c09231aa4df9273c49b7dd67a1dff

**Closed by hrsh7th** 2020-12-15 18:20 UTC
Labels: bug

**Comment by tamago324** [comment] 2020-12-15 21:23
Thank you!
