### ISSUE TITLE
-> does not replace . with clangd

### ISSUE THREAD

**Issue by sarimaleem** [hrsh7th/nvim-compe#382] opened 2021-05-18 20:58 UTC
#### Describe the bug

When using autocomplete with clangd for struct fields in c, the `.` does not get replaced with a` ->`, but rather the `->` gets added after the `.`

#### To Reproduce
my config just holds the default settings:

```
lua << EOF
require'lspconfig'.clangd.setup{}
EOF

let g:compe = {}
let g:compe.enabled = v:true
let g:compe.autocomplete = v:true
let g:compe.debug = v:false
let g:compe.min_length = 1
let g:compe.preselect = 'enable'
let g:compe.throttle_time = 80
let g:compe.source_timeout = 200
let g:compe.incomplete_delay = 400
let g:compe.max_abbr_width = 100
let g:compe.max_kind_width = 100
let g:compe.max_menu_width = 100
let g:compe.documentation = v:true

let g:compe.source = {}
let g:compe.source.path = v:true
let g:compe.source.buffer = v:true
let g:compe.source.calc = v:true
let g:compe.source.nvim_lsp = v:true
let g:compe.source.nvim_lua = v:true
let g:compe.source.vsnip = v:true
let g:compe.source.ultisnips = v:true
```

#### Actual behavior
`struct.fielda`
turns into 
`struct.->field a`
#### Expected behavior
`struct.fielda`
turns into
`struct->field a`

**Comment by ii14** [comment] 2021-05-18 21:00
Duplicate of #156

**Comment by sarimaleem** [comment] 2021-05-19 03:40
Duplicate so I closed it

**Closed** 2021-05-19 03:40 UTC
Labels: bug
