### ISSUE TITLE
Manual completion doesn't respect completeopt

### ISSUE THREAD

**Issue by fsouza** [hrsh7th/nvim-compe#207] opened 2021-02-23 16:38 UTC
Hey there, thank you very much for the continued improvements to nvim-compe!

As of the latest master, whenever I manually trigger completion, my `completeopt` is ignored and `completeopt` is set to `menuone`.

This looks like an intentional change here: https://github.com/hrsh7th/nvim-compe/commit/398b06ccc9863f068e9103a7f8403f363f0d7bcb#diff-34e59c9ed2d73671884669c3870c279c247e447ecd596f57931c49a14c4ba4e0R259-R260

Is this something you'd be willing to change/make optional?

Thanks!

**Comment by hrsh7th** [comment] 2021-02-23 16:41
Good point.

Yes. I was received a feature request and the I thought it's make sense.
But now, I'm considering it should be configurable or restore.

**Comment by datwaft** [comment] 2021-02-23 20:34
Was just about to open an issue about this problem. It always autoselects the first one. Good to see I am not the only with this issue.

**Comment by YorickPeterse** [comment] 2021-02-23 21:54
Since the request was about selecting the first entry, I think making that an option (that's disabled by default) makes the most sense. That way you could do something like `let g:compe = { 'select_first': v:true }` to enable it.

**Comment by hrsh7th** [comment] 2021-02-24 02:20
I don't want to add many options.
But this feature already shipped so We have to add an option...

**Comment by hrsh7th** [comment] 2021-02-24 07:22
Fixed in https://github.com/hrsh7th/nvim-compe/commit/677269cb485d7c7cf64fce43f286e7be12cc0d0f

Now the `completeopt` can be specified in the manual completion.
```
    inoremap <silent><expr><C-Space> compe#complete({ 'completeopt': 'menu,menuone' })
```

**Closed by hrsh7th** 2021-02-24 07:22 UTC
Labels: enhancement, high-priority

**Comment by YorickPeterse** [comment] 2021-02-24 09:31
@hrsh7th Thanks!

**Comment by YorickPeterse** [comment] 2021-02-24 10:56
@hrsh7th I think your change isn't quite working. On commit 6d70803832f7d6c132b18f68aed7591eb802b6bb, manual completion using `compe#complete()` works reliably.

I then tried to use 677269cb485d7c7cf64fce43f286e7be12cc0d0f, with `compe#complete({ 'completeopt': 'menuone' })`. I expected this to match the old behaviour, but it doesn't. Instead, it seems I have to trigger completion multiple times before it even shows up. I can reproduce this quite consistently when using rust-analyzer, with the following file:

```rust
fn main() {
    let foo = 10;
    let bar_foo = 20;
    let xxx_foo = 30;
    let foo_test = 40;
    let hello = 42;
}
```

When trying to complete `foo` on commit 6d70803832f7d6c132b18f68aed7591eb802b6bb, it only takes a few seconds for results to show up, But when using `677269cb485d7c7cf64fce43f286e7be12cc0d0f`, I have to trigger completions multiple times using different inputs (e.g. first `foo` then `hello`) before the menu shows up.

I first thought rust-analyzer may randomly be slow, but I can reproduce this pattern consistently.

**Comment by YorickPeterse** [comment] 2021-02-24 10:59
Specifically: using `master` I have to trigger completion about 7 times before any results show up. On https://github.com/hrsh7th/nvim-compe/commit/6d70803832f7d6c132b18f68aed7591eb802b6bb I only need 2-3 attempts before the results show up.

**Comment by hrsh7th** [comment] 2021-02-24 11:57
I think it will occur if LSP completion delayed.
Because if the user selected one of the items, compe must not update completion-menu.

You can change `let g:compe.source_timeout` option for it.

**Comment by hrsh7th** [comment] 2021-02-24 12:01
I think the feature that is selecting the first-item automatically has a lot of side-effects.
I don't want to add specialized code for it more.

**Comment by fsouza** [comment] 2021-02-24 14:02
Seeing this error now:

```
lua/compe/context.lua:21: attempt to index local 'option' (a nil value)
```

Sent #215.

**Comment by fsouza** [comment] 2021-02-24 14:05
Yeah, after fixing #215, I'm also seeing the issue with completion not being triggered.
